### ISSUE TITLE
Docker image fails to build due to missing `gcc` dependency

### ISSUE THREAD

**Issue by spencerhughes** [rolandu/nextcloud-tests#2]
When building the Docker image, the build fails with the error:
```
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.8 -c lib/zoneinfo_module.c -o build/temp.linux-aarch64-cpython-38/lib/zoneinfo_module.o -std=c99
error: command 'gcc' failed: No such file or directory
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for backports.zoneinfo
```

Research indicates that `gcc` isn't included in the `python:3.8-slim` image to reduce image size.

**Comment by rolandu** [comment]
@spencerhughes : not sure why you get this error and I don't - might be due to different versions. I have accepted your commit and done some other improvements to the build process. This should solve this issue.

**Comment by spencerhughes** [comment]
It's possible it's CPU architecture, since I'm on an M-series Mac.
